/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import com.teclaguna.compilador.Compilador;
import com.teclaguna.compilador.Linea_BE;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keyge
 */
public class CompiladorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CompiladorFrame
     */
    private Compilador compilador = new Compilador();
    
    public CompiladorFrame() {
        initComponents();
        setTitle("Compilador");
        Dimension tamPantalla = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(0, 0, tamPantalla.width, tamPantalla.height - 25);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonALexico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaSimbolos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxaTexto = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxaMensajes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonALexico.setText("Análisis léxico");
        buttonALexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonALexicoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jtTablaSimbolos);

        jtxaTexto.setColumns(20);
        jtxaTexto.setRows(5);
        jScrollPane2.setViewportView(jtxaTexto);

        jtxaMensajes.setColumns(20);
        jtxaMensajes.setRows(5);
        jScrollPane3.setViewportView(jtxaMensajes);

        jLabel1.setText("Consola de errores:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonALexico)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(buttonALexico)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonALexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonALexicoActionPerformed
        // Mensajes del analizador lexico
        jtxaMensajes.setText("ANALISIS DE LEXICO INICIADO....\n");
        compilador.analizarLexico(jtxaTexto.getText());
        actualizarGUIBufferEntrada();
        jtxaMensajes.append("*******Analisis de Lexico terminado*******\n");
//        jtxaMensajes.append(compilador.getTotalErrores(Compilador.ERR_LEXICO)
//                + "  error(es) encontrado(s).\n\n");
    }//GEN-LAST:event_buttonALexicoActionPerformed

    // Metodo para actualizacion de tabla que muestra el buffer de entrada 
    private void actualizarGUIBufferEntrada() {
        String[] nombresCol = {"Complex", "Lexema", "Entrada"};
        Linea_BE[] buffEnt = compilador.getBufferEntrada();
        Object[][] datos = new Object[buffEnt.length][3];

        for (int i = 0; i < buffEnt.length; i++) {
            datos[i][0] = buffEnt[i].getComplex();
            datos[i][1] = buffEnt[i].getLexema();
            datos[i][2] = buffEnt[i].getEntrada();
        }

//        DefaultTableModel modelo = new DefaultTableModel(datos, nombresCol);
        jtTablaSimbolos.setModel(
                new DefaultTableModel(datos, nombresCol) {
                    boolean[] canEdit = new boolean[]{
                        false, false, false
                    };
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit[ columnIndex];
                    }
                });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompiladorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonALexico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtTablaSimbolos;
    private javax.swing.JTextArea jtxaMensajes;
    private javax.swing.JTextArea jtxaTexto;
    // End of variables declaration//GEN-END:variables
}
